{% set name = "torch_geometric" %}
{% set version = "2.3.1" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 454fd0bbc128a17a4b9d15010ba9f66d48ec8cd7277991b888a7770263fa125d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - pyg-lib ==0.2.0
    - pytorch

    # Required deps
    - tqdm
    - numpy
    - scipy
    - jinja2
    - requests
    - pyparsing
    - scikit-learn
    - psutil >=5.8.0

    # Full deps
    - ase
    - h5py
    - numba
    - sympy
    - captum
    - rdflib
    - trimesh
    - networkx
    - graphviz
    - tabulate
    - matplotlib-base
    - scikit-image
    # - pytorch-memlab  # not yet on conda forge
    # - pgmpy  # not yet on conda forge
    - opt_einsum
    - statsmodels

test:
  imports:
    - torch_geometric

about:
  home: https://github.com/pyg-team/pytorch_geometric
  summary: Geometric Deep Learning Extension Library for PyTorch
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pyg-team/pytorch_geometric

extra:
  recipe-maintainers:
    - bubblyorca
    - mxr-conda
    - mikemhenry
    - hadim
